package com.fit2cloud.codedeploy2.client.model;

import java.io.Serializable;

public class CloudServer implements Serializable {
    private String id;

    private String instanceUuid;

    private String workspaceId;

    private String accountId;

    private String instanceId;

    private String instanceName;

    private String imageId;

    private String instanceStatus;

    private String instanceType;

    private String instanceTypeDescription;

    private String region;

    private String zone;

    private String host;

    private String remoteIp;

    private String ipArray;

    private String os;

    private String osVersion;

    private Integer cpu;

    private Integer memory;

    private Integer disk;

    private Long createTime;

    private Long lastSyncTimestamp;

    private String hostname;

    private String managementIp;

    private Integer managementPort;

    private String osInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_server
     *
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.id
     *
     * @return the value of cloud_server.id
     *
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.id
     *
     * @param id the value for cloud_server.id
     *
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_uuid
     *
     * @return the value of cloud_server.instance_uuid
     *
     */
    public String getInstanceUuid() {
        return instanceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_uuid
     *
     * @param instanceUuid the value for cloud_server.instance_uuid
     *
     */
    public void setInstanceUuid(String instanceUuid) {
        this.instanceUuid = instanceUuid == null ? null : instanceUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.workspace_id
     *
     * @return the value of cloud_server.workspace_id
     *
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.workspace_id
     *
     * @param workspaceId the value for cloud_server.workspace_id
     *
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.account_id
     *
     * @return the value of cloud_server.account_id
     *
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.account_id
     *
     * @param accountId the value for cloud_server.account_id
     *
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_id
     *
     * @return the value of cloud_server.instance_id
     *
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_id
     *
     * @param instanceId the value for cloud_server.instance_id
     *
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId == null ? null : instanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_name
     *
     * @return the value of cloud_server.instance_name
     *
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_name
     *
     * @param instanceName the value for cloud_server.instance_name
     *
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.image_id
     *
     * @return the value of cloud_server.image_id
     *
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.image_id
     *
     * @param imageId the value for cloud_server.image_id
     *
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_status
     *
     * @return the value of cloud_server.instance_status
     *
     */
    public String getInstanceStatus() {
        return instanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_status
     *
     * @param instanceStatus the value for cloud_server.instance_status
     *
     */
    public void setInstanceStatus(String instanceStatus) {
        this.instanceStatus = instanceStatus == null ? null : instanceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_type
     *
     * @return the value of cloud_server.instance_type
     *
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_type
     *
     * @param instanceType the value for cloud_server.instance_type
     *
     */
    public void setInstanceType(String instanceType) {
        this.instanceType = instanceType == null ? null : instanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.instance_type_description
     *
     * @return the value of cloud_server.instance_type_description
     *
     */
    public String getInstanceTypeDescription() {
        return instanceTypeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.instance_type_description
     *
     * @param instanceTypeDescription the value for cloud_server.instance_type_description
     *
     */
    public void setInstanceTypeDescription(String instanceTypeDescription) {
        this.instanceTypeDescription = instanceTypeDescription == null ? null : instanceTypeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.region
     *
     * @return the value of cloud_server.region
     *
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.region
     *
     * @param region the value for cloud_server.region
     *
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.zone
     *
     * @return the value of cloud_server.zone
     *
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.zone
     *
     * @param zone the value for cloud_server.zone
     *
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.host
     *
     * @return the value of cloud_server.host
     *
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.host
     *
     * @param host the value for cloud_server.host
     *
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.remote_ip
     *
     * @return the value of cloud_server.remote_ip
     *
     */
    public String getRemoteIp() {
        return remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.remote_ip
     *
     * @param remoteIp the value for cloud_server.remote_ip
     *
     */
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp == null ? null : remoteIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.ip_array
     *
     * @return the value of cloud_server.ip_array
     *
     */
    public String getIpArray() {
        return ipArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.ip_array
     *
     * @param ipArray the value for cloud_server.ip_array
     *
     */
    public void setIpArray(String ipArray) {
        this.ipArray = ipArray == null ? null : ipArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.os
     *
     * @return the value of cloud_server.os
     *
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.os
     *
     * @param os the value for cloud_server.os
     *
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.os_version
     *
     * @return the value of cloud_server.os_version
     *
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.os_version
     *
     * @param osVersion the value for cloud_server.os_version
     *
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.cpu
     *
     * @return the value of cloud_server.cpu
     *
     */
    public Integer getCpu() {
        return cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.cpu
     *
     * @param cpu the value for cloud_server.cpu
     *
     */
    public void setCpu(Integer cpu) {
        this.cpu = cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.memory
     *
     * @return the value of cloud_server.memory
     *
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.memory
     *
     * @param memory the value for cloud_server.memory
     *
     */
    public void setMemory(Integer memory) {
        this.memory = memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.disk
     *
     * @return the value of cloud_server.disk
     *
     */
    public Integer getDisk() {
        return disk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.disk
     *
     * @param disk the value for cloud_server.disk
     *
     */
    public void setDisk(Integer disk) {
        this.disk = disk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.create_time
     *
     * @return the value of cloud_server.create_time
     *
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.create_time
     *
     * @param createTime the value for cloud_server.create_time
     *
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.last_sync_timestamp
     *
     * @return the value of cloud_server.last_sync_timestamp
     *
     */
    public Long getLastSyncTimestamp() {
        return lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.last_sync_timestamp
     *
     * @param lastSyncTimestamp the value for cloud_server.last_sync_timestamp
     *
     */
    public void setLastSyncTimestamp(Long lastSyncTimestamp) {
        this.lastSyncTimestamp = lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.hostname
     *
     * @return the value of cloud_server.hostname
     *
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.hostname
     *
     * @param hostname the value for cloud_server.hostname
     *
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.management_ip
     *
     * @return the value of cloud_server.management_ip
     *
     */
    public String getManagementIp() {
        return managementIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.management_ip
     *
     * @param managementIp the value for cloud_server.management_ip
     *
     */
    public void setManagementIp(String managementIp) {
        this.managementIp = managementIp == null ? null : managementIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.management_port
     *
     * @return the value of cloud_server.management_port
     *
     */
    public Integer getManagementPort() {
        return managementPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.management_port
     *
     * @param managementPort the value for cloud_server.management_port
     *
     */
    public void setManagementPort(Integer managementPort) {
        this.managementPort = managementPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_server.os_info
     *
     * @return the value of cloud_server.os_info
     *
     */
    public String getOsInfo() {
        return osInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_server.os_info
     *
     * @param osInfo the value for cloud_server.os_info
     *
     */
    public void setOsInfo(String osInfo) {
        this.osInfo = osInfo == null ? null : osInfo.trim();
    }
}
